lhosts: Fix host name
由于 localhost 一般为默认的主机名和 127.0.0.1 这一地址的别名，localhost
不应该被直接替换成系统的主机名，目前大多数软件也将 localhost作为本地回环
地址来直接调用。

并且，将所有机器的系统主机名设置为 127.0.0.1 这一地址是不合理的，例如，
一些企业内网会为每台机器提供单独的内网 IP，这些 IP 是映射系统主机名的。
替换为 127.0.0.1 显然不合理而且会造成一些网络连接上的问题。

因此，此次修改不再全局替换 localhost 为系统主机名，而是在更新前，从
hosts 文件中保留下系统主机名的相关映射规则。

同时，做了一些细微的修正：
  * 加入部分注释，确保脚本可读;
  * 调用 bash 而不是 sh;
  * 简化 update_hosts 函数

Issue: https://github.com/racaljk/hosts/issues/691
Signed-off-by: Andy Deng <theandy.deng@gmail.com>

diff --git a/lhosts b/lhosts
--- a/lhosts
+++ b/lhosts
@@ -1,127 +1,141 @@
-#!/bin/sh
-site=https://github.com/racaljk/hosts
+#!/bin/bash
+#
+# lhosts: update your hosts file from https://github.com/racaljk/hosts
+#
 
-thisname=${0##*/}
+myname=${0##*/}
 
-HOSTS=/etc/hosts
-REMOTE="/tmp/hosts.rmt"
+HOSTS="/etc/hosts"
+BACKUP_FILE="/etc/hosts.bak"
+REMOTE_FILE="/tmp/hosts.rmt"
 
 MAIN="https://raw.githubusercontent.com/racaljk/hosts/master/hosts"
 MIRROR="https://coding.net/u/scaffrey/p/hosts/git/raw/master/hosts"
 HOSTS_URL="$MAIN"
 
-NET_TOOL="curl"
+NET_TOOLS="curl"
 QWGET=
 QCURL=
 
-usage() {
-    cat >&2 <<EOL
-提示:
-  可使用 crontab 定时执行脚本 (请确保 sudo 无需输入密码)
+usage()
+{
+	cat <<EOL
+注:
+  可以使用 crontab 定时执行脚本 (root 身份运行或 sudo 无需输入密码)
+  更新前，原 hosts 备份至 $BACKUP_FILE
 
-用法: $thisname [选项]...
-默认从 $site 获取 hosts 文件，
-并更新其中的 localhost 为 `hostname`
-更新前，原 hosts 备份至 /etc/hosts.bak
+用法: $myname [选项]...
 
 选项:
   -w, --wget             使用 wget 下载
-  -m, --mirror           使用 hosts 镜像地址
+  -m, --mirror           从镜像地址获取 hosts
   -q, --quiet            静默模式
-  -u, --url              自定义 hosts 源地址
+  -u, --url <url>        自定义 hosts 源地址
   -h, -1, --help         显示帮助信息并退出
 
 退出状态：
   0  正常
-  1  一般问题 (例如：命令行参数错误)
-  2  严重问题 (例如：文件下载失败)
+  1  命令行参数错误
+  2  文件下载失败
 
 参考:
 
-    $thisname -mq
+    $myname -mq
 
 自定义源：
 
-    $thisname -qu $MIRROR
+    $myname -qu $MIRROR
 
 EOL
 }
 
-hosts_get() {
-    if [ "$NET_TOOL" = "wget" ]; then
-        "$NET_TOOL" $QWGET "$HOSTS_URL" -O "$REMOTE"
-    else
-        # use curl
-        if [ "$QCURL" = "" ]; then
-            echo "正在更新 hosts ..."
+get_hosts()
+{
+	# If the quiet mode is turned off, print some messages.
+	if [ -z "$QCURL" ]; then
+		echo "正在更新 hosts..."
         fi
 
-        "$NET_TOOL" -# $QCURL "$HOSTS_URL" -o "$REMOTE"
-    fi
+	if [ "$NET_TOOLS" = "wget" ]; then
+		# Use Wget to download.
+		"$NET_TOOLS" $QWGET "$HOSTS_URL" -O "$REMOTE_FILE"
+	else
+		# Use cURL to download.
+		"$NET_TOOLS" $QCURL "$HOSTS_URL" -#o "$REMOTE_FILE"
+	fi
 
-    if [ "$?" -ne 0 ]; then
-        echo -e "\nhosts 下载失败" >&2
-        exit 2
-    fi
+	if [ $? -ne 0 ]; then
+		echo "hosts 下载失败" >&2
+		exit 2
+	fi
 }
 
-hosts_update() {
-    local loc="$1"
-    local rmt="$2"
-    local swp="hosts.swp"
-    local bak="/etc/hosts.bak"
-    local begin="# Copyright (c) 2014"
-    local end="# Modified hosts end"
-
-    sed -e "s/localhost/`hostname`/g" "$rmt" > "$swp"
-    rm -f "$rmt"
-
-    sudo cp "$loc" "$bak"
-
-    # check if racaljk hosts, or do nothing
-    if grep -q racaljk "$loc"; then
-        sed -e "/$begin/,/$end/d" "$loc" >> "$swp"
-    fi
-
-    sudo sh -c "cat $swp > $loc"
-    rm -f "$swp"
+backup_hosts()
+{
+	sudo cp -f "$HOSTS" "$BACKUP_FILE"
 }
 
-CMD=`getopt -o wmqu:h1 --long wget,mirror,quiet,url:,help -n \
-    "$thisname" -- "$@"` || exit 1
+update_hosts()
+{
+	local swp="/tmp/hosts.swp"
+	local begin_mark="# Copyright (c) 2014"
+	local end_mark="# Modified hosts end"
+
+	# Reserved host name rules.
+	grep -m 1 $(hostname) "$HOSTS" > "$swp"
+
+	# If racaljk hosts has used, clean racaljk hosts up, and retain
+	# the rest of the hosts rules.
+	#
+	# If not, entire hosts file will be clean up, you should get back
+	# some rules from the backup files on demand.
+	#
+	if grep -q "racaljk" "$HOSTS"; then
+		sed "/$begin_mark/,/$end_mark/d" "$HOSTS" >> "$swp"
+	fi
+
+	cat "$REMOTE_FILE" >> "$swp"
+	sudo cp -f "$swp" "$HOSTS"
+
+	rm -f "$swp" "$REMOTE_FILE"
+}
+
+LONGOPTS="wget,mirror,quiet,url:,help"
+CMD=$(getopt -o wmqu:h1 --long $LONGOPTS -n "$myname" -- "$@") || exit 1
 
 eval set -- "$CMD"
 
 while true; do
-    case "$1" in
-        -w|--wget)
-            NET_TOOL="wget"
-            shift
-            ;;
-        -m|--mirror)
-            HOSTS_URL="$MIRROR"
-            shift
-            ;;
-        -q|--quiet)
-            QWGET=-q
-            QCURL=-s
-            shift
-            ;;
-        -u|--url)
-            HOSTS_URL="$2"
-            shift 2
-            ;;
-        -h|-1|--help)
-            usage
-            exit 0
-            shift
-            ;;
-        --)
-            shift
-            break
-            ;;
-    esac
+	case "$1" in
+		-w|--wget)
+		NET_TOOLS="wget"
+		shift
+		;;
+		-m|--mirror)
+		HOSTS_URL="$MIRROR"
+		shift
+		;;
+		-q|--quiet)
+		QWGET=-q
+		QCURL=-s
+		shift
+		;;
+		-u|--url)
+		HOSTS_URL="$2"
+		shift 2
+		;;
+		-h|-1|--help)
+		usage
+		exit 0
+		shift
+		;;
+		--)
+		shift
+		break
+		;;
+	esac
 done
 
-hosts_get
-hosts_update "$HOSTS" "$REMOTE"
+get_hosts
+backup_hosts
+update_hosts
